

spring.application.name: bank-customers-service

management:
  metrics:
    enable:
      all: false
      http.server.requests: true
      system.cpu.count: true
      executor: true
      httpcomponents: true
  endpoints:
    web:
      base-path: /management
      exposure:
        include: info, health, metrics, prometheus, loggers
      userid: local
      password: password123

secure:
  endpoints:
    - "/api/**"
    - "/jwk/**"
    - "/swagger-ui.htm"
    - "/swagger-resources/**"
    - "/v3/api-docs/**"
    - "/management/health/**"